[phases.setup]
nixPkgs = ["nodejs_20", "npm-9_x"]

[phases.install]
cmds = ["cd client && npm install --include=dev", "cd server && npm install --include=dev"]

[phases.build]
cmds = ["cd client && npm run build"]

[start]
cmd = "cd server && npm start"

[variables]
NPM_CONFIG_PRODUCTION = "false"
NODE_ENV = "production"
